package com.rmpteam.zozh.ui.auth

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.rmpteam.zozh.data.user.UserProfile
import com.rmpteam.zozh.data.user.UserRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch

class RegisterViewModel(private val userRepository: UserRepository) : ViewModel() {

    private val _uiState = MutableStateFlow(RegisterUiState())
    val uiState: StateFlow<RegisterUiState> = _uiState.asStateFlow()

    fun updateUsername(username: String) {
        _uiState.update { it.copy(username = username, errorMessage = null) }
    }

    fun updatePassword(password: String) {
        _uiState.update { it.copy(password = password, errorMessage = null) }
    }

    fun updateConfirmPassword(confirmPassword: String) {
        _uiState.update { it.copy(confirmPassword = confirmPassword, errorMessage = null) }
    }
    
    // Optional: if email is collected
    // fun updateEmail(email: String) {
    //     _uiState.update { it.copy(email = email, errorMessage = null) }
    // }

    fun registerUser() {
        val currentState = uiState.value
        if (currentState.username.isBlank() || currentState.password.isBlank() || currentState.confirmPassword.isBlank()) {
            _uiState.update { it.copy(errorMessage = "Все поля должны быть заполнены") }
            return
        }

        if (currentState.password != currentState.confirmPassword) {
            _uiState.update { it.copy(errorMessage = "Пароли не совпадают") }
            return
        }

        _uiState.update { it.copy(isLoading = true) }

        // Construct UserProfile for registration
        // ID will be generated by the repository/datasource
        // Other fields like weight, height, etc., are set during profile setup
        val userToRegister = UserProfile(
            id = "", // Will be ignored and generated by FakeUserProfileDatasource
            username = currentState.username,
            password = currentState.password
            // email = currentState.email, // if email is collected
        )

        viewModelScope.launch {
            val result = userRepository.register(userToRegister)
            result.fold(
                onSuccess = {
                    _uiState.update {
                        it.copy(
                            isLoading = false,
                            registrationSuccess = true,
                            errorMessage = null
                        )
                    }
                },
                onFailure = { exception ->
                    _uiState.update {
                        it.copy(
                            isLoading = false,
                            errorMessage = exception.message ?: "Ошибка регистрации",
                            registrationSuccess = false
                        )
                    }
                }
            )
        }
    }

    fun onRegistrationHandled() {
        // Reset registrationSuccess flag and potentially other fields if needed
        _uiState.update { it.copy(registrationSuccess = false, errorMessage = null) }
    }
} 